name: Deploy to Firebase Hosting to Demo
'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    if: ${{ github.repository }} == 'karthikmaddirala/Portfolio'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]  # Set this to the version your project uses
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: CI=false yarn build

      - name: Create firebase.json and .firebaserc
        run: |
          echo ${{ secrets.FIREBASE_JSON }} | base64 -d > firebase.json
          echo ${{ secrets.FIREBASERC }} | base64 -d > .firebaserc

      - name: Deploy to Firebase Hosting
