name: Deploy to Firebase Hosting on Prod
'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    if: ${{ github.repository == 'karthikmaddirala/Portfolio' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: CI=false yarn build  # Temporarily disable CI error on warnings

      - name: Create firebase.json and .firebaserc
        run: |
          echo ${{ secrets.FIREBASE_JSON }} | base64 -d > firebase.json
          echo ${{ secrets.FIREBASERC }} | base64 -d > .firebaserc

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting:prod --project=${{ secrets.FIREBASE_PROJECT_NAME }} --token=${{ secrets.FIREBASE_TOKEN }} --non-interactive
